### ISSUE TITLE
Support for remote ollama

### ISSUE THREAD

**Issue by priyanshs** [zeitlings/alfred-ollama#2]
Hi @zeitlings, 
I love the workflow; I tried it on an M1 Macbook Air with 8 GB of RAM. As you can imagine, it completely sucks. I also have a server on which I sometimes play around with larger LLMs. 
Could it be configured to connect to a remote instance serving Ollama? Will it be too much work to modify the workflow? I just got Alfred, and this is a use case I am looking forward to. 

Thanks
priyanshs

**Comment by jdtzmn** [comment]
For anyone else who stumbles on this thread, for the ollama alfred results to work correctly, you must also set an [Alfred environment variable](https://www.alfredapp.com/help/workflows/advanced/variables/#environment) `OLLAMA_HOST=[host]`

**Comment by jdtzmn** [comment]
@zeitlings there still remains the issue that Ollama running detection uses `lsof` which does not support remote Ollama instances. Would you be open to a pull request that switches to using netcat-based methods instead?

**Comment by zeitlings** [comment]
Hi @jdtzmn 

Sure! I have no remote location set up, so I can test it. Maybe it will suffice for you to confirm that this approach works. Try replacing the `lsof` line with this:

```sh
[[ $(
    nc -z ${workflow_host:-localhost} ${workflow_port:-11434} >/dev/null 2>&1
    echo $?
) -eq 0 ]] && is_ollama_running=true
```

It does work on localhost, and if that's all that's required to support your remote Ollama instance, I'm glad to make the necessary changes.

**Comment by jdtzmn** [comment]
I appreciate the fast response! I spent a good amount of time getting this working on a fork of mine. I've opened a PR just now here: https://github.com/zeitlings/alfred-ollama/pull/9
