### ISSUE TITLE
Feat: RAG. Make the chat aware of the local filesystem to answer question about local data

### ISSUE THREAD

**Issue by reyem** [zeitlings/alfred-ollama#3]
Hi @zeitlings,

Awesome work(-flow)! It works okay fast with my dated i9 MacBook. But really useful would be to ingest knowledge of my local filesystem/Documents, so it can answer questions or reasoning using my documents, possibly using spotlight to search for matching files before. Basically a RAG with spotlight.
Somebody built such a thing already, but not with an Alfred workflow. Doing a similar thing within this workflow would be great.

https://medium.com/@pranavdhoolia/building-a-chatgpt-like-search-for-your-macos-with-ollama-and-langchain-ff878c1a82c6

**Comment by zeitlings** [comment]
Hi @reyem!

Thanks for the suggestion and the link. That's a very interesting use case and implementation. However, that goes beyond what I have in mind for this workflow, which is to manage local LLMs and test them. Implementing something like this (with Alfred no less) is no trivial task. I might revisit it sometime in the future, but for now I'm deferring it as not planned. 

For document Q&A, you can check out my [GPT Nexus](https://github.com/zeitlings/ayai-gpt-nexus) workflow. There, you can explicitly add documents as file attachments and chat with them. However, no fine-grained RAG is happening; the contents of the attached document will be injected entirely each time. You can also set up Ollama as "primary" in the environment variables.
