### ISSUE TITLE
Chat history doesn't load

### ISSUE THREAD

**Issue by gg-1997** [zeitlings/alfred-ollama#4]
Using version 2.0.0. When making a new chat and opening chat history with the option + shift button,  the chat history starts loading but the the Alfred search bar disappears, without showing past chat history.

**Comment by gg-1997** [comment]
Hello, I tried changing the modifier but no luck. I don't think its related to the bug in MacOS 15 you linked to.  I also have saving conversations enabled. This what I've been getting with the debugger. 

> /Library/Developer/CommandLineTools/usr/include/swift/module.modulemap: 0:
> /Library/Developer/CommandLineTools/usr/include/swift/bridging.modulemap: 0:
> src/Archive.swift:9:8: error: failed to build module 'Foundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.5 clang-1600.0.30.1)', while this compiler is 'Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)'). Please select a toolchain which matches the SDK.
>   7 | //
>   8 | 
>   9 | import Foundation
>     |        `- error: failed to build module 'Foundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.5 clang-1600.0.30.1)', while this compiler is 'Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)'). Please select a toolchain which matches the SDK.
>  10 | 
>  11 | protocol Inflatable {
> /Users/myname/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/6323CB0D-D40E-48E8-A700-A94376379F5A:3: no such file or directory: ./src/Archive
> 

Interestingly, I think the conversations are being saved in Users/myname/Library Application Support/Alfred/Workflow Data/com.zeitlings.ollama/archive

**Comment by zeitlings** [comment]
Do you have the Xcode Command Line Tools installed?

```bash
xcode-select --install
```
If you have multiple Xcode versions installed, you can switch between them:

```bash
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by gg-1997** [comment]
I managed to find out what it was thanks to your comment. I had Command Line Tools installed, but not Xcode through the Mac App Store. 

When I tried running 
>/usr/bin/xcodebuild -version

I got this: 
>xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

I used the method described by [tjmehta](https://stackoverflow.com/users/645251/tjmehta) and [Naman](https://stackoverflow.com/users/1746118/naman) in this link to make sure.

[https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error](url)

After doing that, it showed up. Thanks for your help.
